/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.member;

import gcom.interfaces.IMember;
import gcom.modules.group.GroupDef;
import gcom.modules.group.Message;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author praneeth
 */
public class ChatWindow extends javax.swing.JDialog {

    private IMember member;

    private MemberWindow memWindow;

    /**
     * Creates new form ChatWindow
     *
     * @param memWindow
     * @param modal
     */
    public ChatWindow(MemberWindow memWindow, boolean modal, IMember member) {
        super(memWindow, modal);
        this.member = member;
        this.memWindow = memWindow;
        initComponents();
        setTitle(memWindow.getMember().getName() + " : Group Chat");
        setLocationRelativeTo(memWindow);
    }

    public void recieveMessage(Message message) throws RemoteException {
        updateChat(message.getSource().getName() + "\t : " + message.getMessage());
        focusChat(true);
    }

    public void changeMemberCount(int count) {
        lblMemCount.setText(count + " Members Online");
    }

    private void updateChat(String msg) {
        txtHistory.setText(txtHistory.getText() + msg + "\n");
    }

    private void focusChat(boolean focus) {
        if (focus) {
            txtChat.setText(null);
            txtChat.setForeground(Color.BLACK);
        } else {
            txtChat.setText("Type your text here...");
            txtChat.setForeground(Color.GRAY);
        }
    }

    private void focusChat() {
        if (txtChat.getText().trim().equalsIgnoreCase("Type your text here...")) {
            txtChat.setText(null);
            txtChat.setForeground(Color.BLACK);
        } else if (txtChat.getText().trim().equalsIgnoreCase("")) {
            txtChat.setText("Type your text here...");
            txtChat.setForeground(Color.GRAY);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistory = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        lblMemCount = new javax.swing.JLabel();

        setTitle("Group Chat");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logo.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("GCom Chat");

        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        txtHistory.setColumns(20);
        txtHistory.setRows(5);
        jScrollPane1.setViewportView(txtHistory);

        jSplitPane1.setTopComponent(jScrollPane1);

        txtChat.setColumns(20);
        txtChat.setRows(3);
        txtChat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtChatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtChatFocusLost(evt);
            }
        });
        txtChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtChatKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtChat);

        jSplitPane1.setRightComponent(jScrollPane2);

        lblMemCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMemCount.setText("3 Members Online");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblMemCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMemCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtChatKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            try {
                String msg = txtChat.getText();
                Message message;
                GroupDef groupDef = member.getParentGroup().getGroupDef();
                message = new Message(member.getParentGroup().getGroupName(), member, null, msg, groupDef.getMultType(), groupDef.getOrdType());

                member.multicastMessages(message, true);
                memWindow.multicastChat(message);

            } catch (RemoteException ex) {
                Logger.getLogger(ChatWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtChatKeyPressed

    private void txtChatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChatFocusGained
        focusChat(true);
    }//GEN-LAST:event_txtChatFocusGained

    private void txtChatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtChatFocusLost
        focusChat(false);
    }//GEN-LAST:event_txtChatFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        txtChat.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        changeMemberCount(memWindow.getContacts().size());
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblMemCount;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextArea txtHistory;
    // End of variables declaration//GEN-END:variables

}
