/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MemberWindow.java
 *
 * Created on Dec 5, 2013, 6:36:59 PM
 */
package gui.member;

import gui.SingleChat;
import java.awt.Color;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;


/**
 *
 * @author Praneeth
 */
public class MemberWindow extends javax.swing.JFrame {

    /** Creates new form MemberWindow */
    ArrayList<String> contacts;

    public MemberWindow() {
        initComponents();
        // setLocationRelativeTo(null);
        setIconImage(new ImageIcon(MemberWindow.class.getResource("/pics/logo.png")).getImage());
        contacts = getContacts();
        fillContacts(contacts);
        lstContacts.setCellRenderer(new myRenderer());
    }

    private void fillContacts(ArrayList<String> contacts) {
        DefaultListModel l = new DefaultListModel();
        Vector v = new Vector();
        int c = 0;
        for (int i = 0; i < contacts.size(); i++) {
            JLabel lb = new JLabel(contacts.get(i));
            lb.setIcon(new ImageIcon(new ImageIcon(MemberWindow.class.getResource("/pics/online.png")).getImage()));
            System.out.println(contacts.get(i));
            //lstContacts.add(j);
            v.add(lb);
        }
        lstContacts.setListData(v);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactListPopUp = new javax.swing.JPopupMenu();
        refreshList = new javax.swing.JMenuItem();
        logoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstContacts = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mnuMainMenu = new javax.swing.JMenuBar();
        toolsMenu = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenu();

        refreshList.setMnemonic('r');
        refreshList.setText("Refresh");
        contactListPopUp.add(refreshList);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GCom Chat");
        setLocationByPlatform(true);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/logo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel1.setText("Praneeth Nilanga Peiris");

        cmbStatus.setFont(new java.awt.Font("Dialog", 0, 12));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Online", "Away", "Busy", "Invisible" }));

        lstContacts.setFont(new java.awt.Font("Dialog", 0, 14));
        lstContacts.setComponentPopupMenu(contactListPopUp);
        lstContacts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstContactsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstContacts);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSearch.setBackground(new java.awt.Color(-986896,true));
        txtSearch.setForeground(new java.awt.Color(-8355712,true));
        txtSearch.setText("Search Contacts");
        txtSearch.setBorder(null);
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/search.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        toolsMenu.setMnemonic('F');
        toolsMenu.setText("File");
        mnuMainMenu.add(toolsMenu);

        viewMenu.setMnemonic('V');
        viewMenu.setText("View");
        mnuMainMenu.add(viewMenu);

        aboutMenu.setMnemonic('A');
        aboutMenu.setText("About");
        mnuMainMenu.add(aboutMenu);

        setJMenuBar(mnuMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(cmbStatus, 0, 234, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ArrayList<String> getContacts() {
        ArrayList<String> c = new ArrayList<String>();
        try {
            BufferedReader br = new BufferedReader(new FileReader("contacts.txt"));
            while (br.ready()) {
                c.add(br.readLine().trim());
            }
        } catch (Exception ex) {
            Logger.getLogger(MemberWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        return c;
    }
    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        if (txtSearch.getText().trim().equalsIgnoreCase("Search Contacts")) {
            txtSearch.setText(null);
            txtSearch.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        if (txtSearch.getText().trim().equalsIgnoreCase("")) {
            txtSearch.setText("Search Contacts");
            txtSearch.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void lstContactsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstContactsMouseClicked
        if (evt.getClickCount() == 2 && lstContacts.getSelectedIndex() != -1) {
            SingleChat c = new SingleChat(this, false, lstContacts.getSelectedValue().toString());
            c.setVisible(true);
        }
    }//GEN-LAST:event_lstContactsMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String txt = txtSearch.getText().trim();
        if (txt.isEmpty()) {
            fillContacts(contacts);
        } else {
            ArrayList<String> c = new ArrayList<String>();
            for (int i = 0; i < contacts.size(); i++) {
                String t = contacts.get(i);
                if (t.toLowerCase().contains(txt.toLowerCase())) {
                    c.add(t);
                }
            }
            fillContacts(c);
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MemberWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JPopupMenu contactListPopUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JList lstContacts;
    private javax.swing.JMenuBar mnuMainMenu;
    private javax.swing.JMenuItem refreshList;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
class myRenderer extends DefaultListCellRenderer {

    @Override
    public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        //JLabel l = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (value instanceof JLabel) {
            this.setText(((JLabel) value).getText());
            this.setIcon(((JLabel) value).getIcon());
            this.setBackground(isSelected ? Color.GRAY : Color.white);
            //this.setForeground(isSelected ? Color.white : Color.black);
        }
        return this;
    }
}
